### ISSUE TITLE
heldOrderRoutingPublicReport's materialAspects truncated after '.'

### ISSUE THREAD

**Issue by bsandlin** [sec-gov/oh#1]
Thank you for setting up this GitHub repository, I would like to report a regression in the marked-pdf version of the renderer.

The `heldOrderRoutingPublicReport`'s `materialAspects` text will be truncated if it contains a `'.'` period.

`<materialAspects>[Insert discussion of the material ... aspects of the relationship with this ... venue pursuant to rule 606(a)(1)(iv).]</materialAspects>`

Renders as
   
`[Insert discussion of the material .`

See [samples/606a1_held_order_public_report.xml](https://github.com/sec-gov/oh/blob/marked-pdf/samples/606a1_held_order_public_report.xml)

**Comment by sec-gov** [comment]
Fixed
