### ISSUE TITLE
notHeldOrderHandlingCustomerReport does not display customer or startDate/endDate in title

### ISSUE THREAD

**Issue by bsandlin** [sec-gov/oh#2]
Hello, I would like to report a regression in the marked-pdf version of the renderer.  `customer` and `startDate` / `endDate` are not being included in the title for `notHeldOrderHandlingCustomerReport`.

Title area should render like this
```
B. Roker - Not-Held NMS Stocks Order Handling Report 
Generated on Mon Jun 01 2020 17:55:48 GMT-0500 (Central Daylight Time)
For C. Schtumer
Reporting Period 2019-12-01 to 2020-05-31
```

See [samples/606b3_empty.xml](https://github.com/sec-gov/oh/blob/marked-pdf/samples/606b3_empty.xml)

**Comment by bsandlin** [comment]
Please refer to this [diff](https://github.com/sec-gov/oh/compare/marked-pdf...bsandlin:b3subtitle?expand=1) for a possible fix. 

I don't have access to any tools to verify the PDF/UA markup is being inserted correctly.

**Comment by sec-gov** [comment]
Fixed
