### ISSUE TITLE
Length of <bd> element

### ISSUE THREAD

**Issue by bsandlin** [sec-gov/oh#4]
Hi there

  The `<bd>` element's max length was changed from 80 to 50 (in the October release I think), can you change the limit back to 80? We have encountered problems with broker's names needing to be altered to fit within the 50 char limit.  There is a note in the `CHANGELOG` about increasing this to 80 in the March release.

Thank you

```xml
  <xs:simpleType name="BrokerDealerNameType">
    <xs:annotation>
      <xs:documentation xml:lang="en"> Name of the reporting broker-dealer of up to 50 characters with white space normalized. </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="50"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>
```

**Comment by sec-gov** [comment]
You are right.  This is like the other regressions that should be fixed shortly.
