### ISSUE TITLE
606a1_held_order_public_report Summary table values not displayed when convert to PDF

### ISSUE THREAD

**Issue by LaiFaiLee** [sec-gov/oh#7]
Hello, 

After some initial testing with the new XML schema published on 12/19/2020, we are finding that the Summary section is not properly populating – it is populating with blanks(--) on the 606a1_held_order_public_report.  We expect these fields to be populated with numeric values.

This is the filename in question:

In the oh-20201219 folder- File Name **Rule606ReportGenerator.js**
Line Number: **813**

**Current SEC Code published on 12/19/2020:**
function getPublicRoutingBody(section, monthVal, year) { // a1
    var empty = true;
    for (var i=0;**i<a1SummaryTableTags[i]**;i++) {
        if (NS != getElementValueByMonth(a1SummaryTableTags[i],section, monthVal, year)) {
            empty = false;
            break;
        }
    }

**Tweak by our development team :**  This minor tweak on Line 813 appears to resolve the display issue.
function getPublicRoutingBody(section, monthVal, year) { // a1
    var empty = true;
    for (var i=0;**i<a1SummaryTableTags.length**;i++) {
        if (NS != getElementValueByMonth(a1SummaryTableTags[i],section, monthVal, year)) {
            empty = false;
            break;
        }
    }
Thank you

**Comment by sec-gov** [comment]
Fixed, thanks

**Comment by LaiFaiLee** [comment]
Hello,

Thank you for the prompt response.  Is the fix only within the source code file?  We just checked the link on the https://www.sec.gov/structureddata/dera_taxonomies this still contains the Report Renderer from 12/19/2020.  Will a new version be published soon?

[cid:image001.png@01D6E814.95AFBA80]

Thanks,
Lai Fai Lee

**Comment by sec-gov** [comment]
Yes, and yes.
