### ISSUE TITLE
606 B1 Report not displaying the execution timestamps 

### ISSUE THREAD

**Issue by LaiFaiLee** [sec-gov/oh#9]
Hello, the new version of the File Name: Rule606ReportGenerat bor.js (located in oh-20210115 folder) is currently not displaying the execution timestamp field on the fthe 606 B1 report when converting XML schema.

File** Name: Rule606ReportGenerator.js (located in oh-20210115 folder)
**Old code:** Line Number 319
} else if (rtChild.tagName == **b1RouteTags[2])** { /* b1RouteTags = [ 'venueName', 'mic', 'mpid', 'transaction' ] */
transactions.push(rtChild);
}

**New code**(after change done): Line number 319 changed b1RouteTags[2] --> b1RouteTags[3]
 } else if (rtChild.tagName == **b1RouteTags[3])** { /* b1RouteTags = [ 'venueName', 'mic', 'mpid', 'transaction' ] */
transactions.push(rtChild);
}

**Comment by sec-gov** [comment]
Thank you for reporting this.

**Comment by sec-gov** [comment]
Fixed
